/**
 * Define la serie de acciones que esta pasando en la app
 */

export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const GET_PROYECTOS = 'GET_PROYECTOS';
export const ADD_PROYECTO = 'ADD_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL'
export const FORMULARIO_TAREAS = 'FORMLUARIO_TAREA'
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO'
export const PROYECTO_ERROR = 'PROYECTO_ERROR'

// tareas
export const TAREAS_PROYECTO = 'TAREA_PROYECTO'
export const AGREGAR_TAREA = 'AGREGAR_TAREA'
export const VALIDAR_TAREA = 'VALIDAR_TAREA'
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA'
export const ESTADO_TAREA = 'ESTADO_TAREA'
export const TAREA_ACTUAL = 'TAREA_ACTUAL'
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA'
export const LIMPIAR_TAREAS = 'LIMPIAR_TAREAS'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

export const REGISTRO_OK = 'REGISTRO_OK'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'